[project]
name = "clientz"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "llmada>=0.1.9",
    "numpy>=2.2.5",
    "querypipz>=0.1.5",
    "sse-starlette>=2.3.4",
    "uvicorn>=0.34.2",
]
